### ISSUE TITLE
Input Image Size

### ISSUE THREAD

**Issue by Dratlan** [IvanDrokin/torch-conv-kan#9]
I use u2kagnet(3, 3) for testing. If the input tensor size have the same w and h, things go right. while for w>h or h>w,I got the error below：
/workspace/nas-data/code/gan_research-dev/pix2pixHD/models/kan/models/u2kanet.py in forward(self, x)
     56         for layer_index, layer in enumerate(self.decoder_list):
     57             skip = encoder_list.pop()
---> 58             x_dec = layer(torch.cat((x_dec, skip), 1))
     59             if layer_index < self.depth - 2:
     60                 x_dec = self.upsample(x_dec)

RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 10 but got size 9 for tensor number 1 in the list.
the input tensorsize is torch.randn(1,3,256,144), if it doesn't support for image with different  w and h?

**Comment by IvanDrokin** [comment]
@Dratlan Hi there! the image input sizes should be divisible on if I remember correctly 16 (or maybe 32), please check out your image input sizes and adjust according to this rule

**Comment by Dratlan** [comment]
It should be 32, Thanks

**Comment by Dratlan** [comment]
One more question, compared to original u2net, u2kagnet has lower trainable parameters, but for training, it needs more gpu_memory, I'm confusing about this.

**Comment by IvanDrokin** [comment]
@Dratlan It's because of Gram polynomials computed on each layer, this requires (N+1) more memory per layer to store the polynomials, where N is a polynomial degree. Basically, any KAN-based convolutions require more memory than vanilla convolutions

**Comment by Dratlan** [comment]
> polynomial

Got it! Thank you.
